name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

workflow_dispatch()

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: TASK3
      run: docker build . --file Dockerfile --tag github_action_image:$(date +%s)
